"""Email Notifier — sends notification emails via SMTP.

Requires SMTP settings to be configured in app.config.settings.
When NOTIFY_ENABLED is False, emails are logged but not sent.
"""

from __future__ import annotations

import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import TYPE_CHECKING

from app.config.settings import settings
from app.notifications.models import Notification

if TYPE_CHECKING:
    pass

logger = logging.getLogger(__name__)


class EmailNotifier:
    """Sends notification emails via SMTP."""

    def __init__(self) -> None:
        self._host = settings.SMTP_HOST
        self._port = settings.SMTP_PORT
        self._user = settings.SMTP_USER
        self._password = settings.SMTP_PASSWORD
        self._from = settings.SMTP_FROM
        self._enabled = settings.NOTIFY_ENABLED and bool(self._host)

    @property
    def is_configured(self) -> bool:
        """Return True if SMTP settings are configured."""
        return bool(self._host and self._user and self._password)

    def _build_subject(self, notification: Notification) -> str:
        """Build a human-readable subject line from alerts."""
        if not notification.alerts:
            return "NF Restro Insights — Daily Update"

        # Prioritize critical/high alerts
        critical = [a for a in notification.alerts if a.severity == "critical"]
        high = [a for a in notification.alerts if a.severity == "high"]

        if critical:
            return f"🚨 NF Restro Alert: {critical[0].title}"
        if high:
            return f"⚠️ NF Restri Alert: {high[0].title}"

        return f"📊 NF Restro Insights — {len(notification.alerts)} update(s)"

    def _build_html_body(self, notification: Notification) -> str:
        """Build an HTML email body from alerts."""
        parts = [
            "<html><body style='font-family: Arial, sans-serif; padding: 20px;'>",
            "<h2>NF Restro AI Insights</h2>",
            "<p>Here are the latest insights for your restaurant:</p>",
            "<hr>",
        ]

        severity_colors = {
            "critical": "#dc3545",
            "high": "#fd7e14",
            "medium": "#ffc107",
            "low": "#28a745",
        }

        for alert in notification.alerts:
            color = severity_colors.get(alert.severity, "#6c757d")
            parts.append(
                f"<div style='border-left: 4px solid {color}; "
                f"padding: 10px; margin: 10px 0; background: #f8f9fa;'>"
                f"<strong>{alert.title}</strong> "
                f"<span style='color: {color};'>({alert.severity.upper()})</span>"
                f"<p>{alert.detail}</p>"
            )
            if alert.recommendation:
                parts.append(
                    f"<p><em>💡 {alert.recommendation}</em></p>"
                )
            parts.append("</div>")

        parts.append(
            "<hr>"
            "<p style='color: #6c757d; font-size: 12px;'>"
            "Generated by NF Restro AI Analytics. "
            "<a href='https://auraos.com/dashboard'>View Dashboard</a>"
            "</p>"
            "</body></html>"
        )

        return "\n".join(parts)

    def _build_plain_body(self, notification: Notification) -> str:
        """Build a plain-text email body."""
        lines = ["AuraOS AI Insights", "=" * 30, ""]

        for alert in notification.alerts:
            lines.append(f"[{alert.severity.upper()}] {alert.title}")
            lines.append(f"  {alert.detail}")
            if alert.recommendation:
                lines.append(f"  → {alert.recommendation}")
            lines.append("")

        lines.append("Generated by AuraOS AI Analytics")
        return "\n".join(lines)

    async def send(self, notification: Notification, to_email: str) -> bool:
        """Send a notification via email.

        Args:
            notification: The notification to send.
            to_email: Recipient email address.

        Returns:
            True if sent successfully, False otherwise.
        """
        if not self._enabled:
            logger.info(
                "Email notifications disabled — would send to %s: %s",
                to_email,
                self._build_subject(notification),
            )
            return True  # Not an error — just disabled

        if not self.is_configured:
            logger.warning("SMTP not configured, cannot send email to %s", to_email)
            notification.error = "SMTP not configured"
            return False

        try:
            msg = MIMEMultipart("alternative")
            msg["Subject"] = self._build_subject(notification)
            msg["From"] = self._from
            msg["To"] = to_email

            msg.attach(MIMEText(self._build_plain_body(notification), "plain", "utf-8"))
            msg.attach(MIMEText(self._build_html_body(notification), "html", "utf-8"))

            # Run blocking SMTP in a thread to avoid blocking the event loop
            import asyncio
            await asyncio.to_thread(self._send_sync, msg, to_email)

            logger.info("Email sent to %s: %s", to_email, msg["Subject"])
            notification.sent = True
            return True

        except Exception:
            logger.exception("Failed to send email to %s", to_email)
            notification.error = "SMTP delivery failed"
            return False

    def _send_sync(self, msg: MIMEMultipart, to_email: str) -> None:
        """Synchronous SMTP send (runs in a thread)."""
        with smtplib.SMTP(self._host, self._port, timeout=15) as server:
            server.starttls()
            server.login(self._user, self._password)
            server.send_message(msg)
